# Generated by Django 3.0.5 on 2020-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_simulator_app', '0003_auto_20200902_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_value',
            field=models.IntegerField(),
        ),
    ]
