# Generated by Django 3.0.5 on 2020-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_simulator_app', '0006_stock_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=20000),
        ),
    ]
